DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
ID INT NOT NULL AUTO_INCREMENT
, VERSION INT NOT NULL DEFAULT 0
, NAME VARCHAR(60) NOT NULL
, PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS TODO;
CREATE TABLE TODO (
ID INT NOT NULL AUTO_INCREMENT
, VERSION INT NOT NULL DEFAULT 0
, DESCRIPTION VARCHAR(60) NOT NULL
, DONE BIT NOT NULL DEFAULT FALSE
, USER_ID INT NOT NULL
, PRIMARY KEY (ID)
, FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);